### ISSUE TITLE
Solutions - 102. Binary Tree Level Order Traversal

### ISSUE THREAD

**Issue by Srijita-Mandal** [wingkwong/leetcode-the-hard-way#124]
@wingkwong I would like to work on this issue to solve the problem with explanation. Please assign me for this.

**Comment by wingkwong** [comment]
For solutions, we welcome all people to contribute. Go ahead and create a PR.

**Comment by wingkwong** [comment]
For Solutions, no need to create an issue. Submit a PR directly.
