### ISSUE TITLE
Collections Introduction/Index page is not up to date 

### ISSUE THREAD

**Issue by Exoutia** [wingkwong/leetcode-the-hard-way#135]
[collections/index.md](https://github.com/wingkwong/leetcode-the-hard-way/tree/main/collections/index.md) Can I fix it for hacktober fest 
- I will add some basic categories like array, linked list, hash-map etc 
- And add some problems 
- after that people can add different easy and introductory problems for it

Is there any suggestion on how to categorize  problem you have cause I think single problems can be of multiple category so do you have any reference i should follow

**Comment by wingkwong** [comment]
![image](https://user-images.githubusercontent.com/35857179/193445286-f391fff3-8c6b-4fe3-9884-0b4a5d1fd979.png)

What's that?

**Comment by wingkwong** [comment]
Please ping me in discord.

**Comment by wingkwong** [comment]
1. You may elaborate more what this section does. For example, for collection, it provides templates for users to reference and use it directly. Supposing they should know the topic before using it. 
2. No need to add problems on index pages.

**Comment by Exoutia** [comment]
Ok will do it 👍
