### ISSUE TITLE
Update current binary Search write up 

### ISSUE THREAD

**Issue by ShivaRapolu01** [wingkwong/leetcode-the-hard-way#137]
Binary search is a very important concept and once ones understands it correctly it feels really good while implementing. I want to work on improving current binary search article and provide a one stop beginner guide to binary search covering major mistakes and problems

**Comment by ShivaRapolu01** [comment]
I want to contribute this under Hactoberfest 2022 . Please assign this to me if you like the idea

**Comment by wingkwong** [comment]
Duplicate #125
