### ISSUE TITLE
Tutorial writeup - Kadane's algorithm 

### ISSUE THREAD

**Issue by ShivaRapolu01** [wingkwong/leetcode-the-hard-way#138]
I want to contribute this issue under Hactoberfest 2022. Please assign this to me @wingkwong

**Comment by wingkwong** [comment]
Go ahead. Please read (the contribution guide](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) first.

**Comment by wingkwong** [comment]
@Vidhanjain143 Sorry. It's taken.
