### ISSUE TITLE
Solution Writeup- Merge Sorted Array

### ISSUE THREAD

**Issue by deepanshu-rawat6** [wingkwong/leetcode-the-hard-way#142]
@wingkwong I would be happy to write solution for `Merge Sorted Array` which comes under the category of `solutions/0000-0099` and I want to add java codes in 2 approaches.
Can you please assign me this issue? Ma'am please add this under `hacktoberfest`

**Comment by wingkwong** [comment]
For solutions, just go ahead and submit PR. No need to create issue.
