### ISSUE TITLE
Tutorial Writeup - LC516 Longest Palindromic Subsequence

### ISSUE THREAD

**Issue by chinmayayy** [wingkwong/leetcode-the-hard-way#147]
Hi @wingkwong I would like to contribute the solution writeup to this issue under Hactoberfest 2022. Kindly assign this to me, thanks.

**Comment by wingkwong** [comment]
Which location you would propose for that markdown?

**Comment by wingkwong** [comment]
For solutions, just go ahead and submit PR. No need to create issue.
