### ISSUE TITLE
Dijkstra's Algorithm

### ISSUE THREAD

**Issue by Kavita613** [wingkwong/leetcode-the-hard-way#183]
Dijkstra Algorithm helps to find the shortest path in a graph.

I will provide the proper explanation and code for this algorithm.

**Comment by Kavita613** [comment]
Kindly assign this issue to me.

**Comment by wingkwong** [comment]
@Kavita613 I mean walk through the problem in the above markdown.

**Comment by wingkwong** [comment]
@Vasudeva-bit Currently I only wrote a short overview in `tutorials/graph-theory/dijkstra.md`.

**Comment by Vasudeva-bit** [comment]
So, shall I add the code? and technical details if needed!

**Comment by wingkwong** [comment]
@Kavita613 are you modifying `tutorials/graph-theory/dijkstra.md`?

**Comment by Kavita613** [comment]
@wingkwong I'd love to, but I can't. Still, if you want me to modify the file then I will do it.

**Comment by wingkwong** [comment]
@Vasudeva-bit @Kavita613 you guys may ping each other in discord to split the task.

**Comment by wingkwong** [comment]
Unassigned due to inactivity.

**Comment by ShadyResurrected** [comment]
Hello, Can you assign me this issue?

**Comment by wingkwong** [comment]
@ShadyResurrected Ping me in Discord for the discussion.
