### ISSUE TITLE
Tutorial Writeup - Reorganize String problem

### ISSUE THREAD

**Issue by Pranathi-star** [wingkwong/leetcode-the-hard-way#199]
I will provide an intuitive and easy to understand solution for the Reorganize string problem that is a Medium level problem on Leetcode. Please assign it to me.

**Comment by wingkwong** [comment]
Do you want to contribute tutorial writeup or solution writeup? can you show some LC problems on this topic?

**Comment by wingkwong** [comment]
For solution contribution, feel free to submit a PR. no need to create an issue.
