### ISSUE TITLE
Tutorial Writeup-N-Queens

### ISSUE THREAD

**Issue by M-Rahul1** [wingkwong/leetcode-the-hard-way#233]
I would explain it breifly.
Assign it to me @wingkwong

**Comment by wingkwong** [comment]
which markdown are you going to work on?

**Comment by M-Rahul1** [comment]
tutorials/basic-topics/(new)N-queens

**Comment by M-Rahul1** [comment]
markdown: [tutorials/basic-topics](url)

**Comment by wingkwong** [comment]
prefer a solution writeup instead. or supplement in `tutorials/basic-topics/backtracking.md`

**Comment by M-Rahul1** [comment]
OK I'll write a solution

**Comment by wingkwong** [comment]
For solutions, no need to create an issue. You can directly submit a PR.
