### ISSUE TITLE
Add contributors profile into README.md

### ISSUE THREAD

**Issue by sb-decoder** [wingkwong/leetcode-the-hard-way#236]
I want to add all contributors profile in a contributor section in your README.md .

**Comment by wingkwong** [comment]
I don't see the point of adding that while there are two places showing that info

![image](https://user-images.githubusercontent.com/35857179/194737511-af82166b-405c-4996-ab13-3062607435c9.png)

https://github.com/wingkwong/leetcode-the-hard-way/graphs/contributors
