### ISSUE TITLE
adding contributers image in readme file

### ISSUE THREAD

**Issue by Beast71421** [wingkwong/leetcode-the-hard-way#242]
![image](https://user-images.githubusercontent.com/78417225/194750534-2e7c4fb0-48eb-4642-9f28-ee0f615cd80d.png)
like this

and can you please add the label hacktoberfest, hacktoberfest-accepted

**Comment by wingkwong** [comment]
See https://github.com/wingkwong/leetcode-the-hard-way/issues/236
