### ISSUE TITLE
Application links visibility hidden while hovering on the main page

### ISSUE THREAD

**Issue by vigneshshiv** [wingkwong/leetcode-the-hard-way#294]
## Links Visibility hidden

In the main page, bottom section while hovering any of the links, the text got disappeared. It includes general and Links section. 

Checkout the below image, I hovered on Github link, the text is disappeared and href is shown bottom left. 

![image](https://user-images.githubusercontent.com/10242660/199150952-0e839c85-db1f-400a-8216-96e36989405d.png)

**Comment by wingkwong** [comment]
Thanks for reporting. Will take a look.
