### ISSUE TITLE
Problem 0345 tagged under wrong solution category range

### ISSUE THREAD

**Issue by vigneshshiv** [wingkwong/leetcode-the-hard-way#317]
## Solution 

Problem 0345 tagged under wrong solution category range, Is there any reason why it's tagged, If not, Please correct it. 

![image](https://user-images.githubusercontent.com/10242660/202758011-58a4392f-9b4e-47f1-b21f-87551c46ab09.png)

**Comment by wingkwong** [comment]
Good Catch. Fixed.
