### ISSUE TITLE
[UI] Footer elements Visibility

### ISSUE THREAD

**Issue by MrBehl06** [wingkwong/leetcode-the-hard-way#393]
## Suggestion 

[UI]There is an issue while hovering on the footer elements. Its Color Is not visible while hovering over it we can change the color so that it will look nice.  

Current Behaviour
<img width="1135" alt="Untitled 3" src="https://user-images.githubusercontent.com/101118926/211209582-ad73ba86-d9bc-428f-bfe3-83818d509f20.png">

Expected Behaviour 
<img width="1297" alt="Screenshot 2023-01-08 at 22 38 29" src="https://user-images.githubusercontent.com/101118926/211209533-c4c70a3a-aaaa-4acd-b59f-ea3696375aa4.png">

## Solution 
We can change the color as shown above 

You **DON'T** need to create an issue and ask for assignment. Just create a pull request. Issues created for solutions will be closed directly.

**Comment by MrBehl06** [comment]
If you find this issue valid then. Please assign this issue to me.

**Comment by wingkwong** [comment]
Assigned. The color in expected behaviour seems not correct as well. It was used previously. Please pull the latest changes to check the color code.

**Comment by MrBehl06** [comment]
Color code: #00bfff 
Please check it once , if you have any suggestions let me know.
<img width="200" alt="Screenshot 2023-01-09 at 13 00 54" src="https://user-images.githubusercontent.com/101118926/211259044-f56cfe63-2cc4-44d1-b2ce-28dfbb7de0b4.png">

**Comment by MrBehl06** [comment]
@wingkwong The colour will appear after we hover over it.

**Comment by MrBehl06** [comment]
@wingkwong  it will be the same because, in the light mode, we didn't change the background colour of the footer. You can check it 
<img width="1295" alt="Screenshot 2023-01-09 at 15 19 22" src="https://user-images.githubusercontent.com/101118926/211280739-b24e931e-039a-4fa3-ade0-d20dbaeb088e.png">

**Comment by wingkwong** [comment]
It looks good. Can you make a PR?

**Comment by MrBehl06** [comment]
Yes, will raise a PR in sometime.
