### ISSUE TITLE
[UI] Drop down menu inconsistency

### ISSUE THREAD

**Issue by ColeB2** [wingkwong/leetcode-the-hard-way#394]
## Suggestion

For smaller viewpoints with the collapsed hamburger menu, the navbar-icon CSS class overwrites the standard behaviour and misaligns the icons it is attached to.

Current Behaviour:
![dropdownissue](https://user-images.githubusercontent.com/50831824/211328831-37b89c63-0ffa-478c-b38f-8e00235c7ee6.png)

Expected Behaviour:
![expecteddropdown](https://user-images.githubusercontent.com/50831824/211328641-79a769f9-a94b-4918-a779-a244c9ef6454.png)

## Solution 

We can wrap the existing navbar CSS in a media tag at the problem pixel width ie: 
@media screen and (min-width: 997px) {<existing navbar-icon css>}
Which allows the functionality to remain the same for larger viewports and work the same with the other items on smaller view ports.

**Comment by wingkwong** [comment]
PR is welcome.
