### ISSUE TITLE
Add a button to toggle between full-screen mode and normal mode

### ISSUE THREAD

**Issue by sceary-expert** [wingkwong/leetcode-the-hard-way#59]
![image](https://user-images.githubusercontent.com/84634405/192695921-9c886cde-505e-4a94-a22f-eafe7e1dedc3.png)
## If you add a button that can hide the topics window on the left then the main content can be more visible( as shown in the image below)
![image](https://user-images.githubusercontent.com/84634405/192696273-203bebc8-e491-48cb-9123-9f934c013d8d.png)

**Comment by i-dipanshu** [comment]
Hello @wingkwong 
I'd to love to work on this issue and hopefully get it going before 1st of october
If possible please do add `hacktoberfest` label for this issue

**Comment by ShivaRapolu01** [comment]
I would like to give this a shot., please assign me

**Comment by i-dipanshu** [comment]
This is already resolved. 
I've been waiting for 1st oct to make the PR.
You're welcome to look into other issue listed and resolve it.

**Comment by i-dipanshu** [comment]
Hey @wingkwong 
I would not see it that way 
Through Hacktoberfest i came to know about this amazing project which perfectly matches my skillset.
I am planning to become regular contributor mainly in Development aspects.
And I didn't make PR because the countdown is just two days away
However, I'm really sorry

**Comment by ShivaRapolu01** [comment]
@i-dipanshu but you didn't request to assign it to you before. Without this others can't know whether someone is already is working on it or not. @wingkwong Let @i-dipanshu raise PR for this?

**Comment by wingkwong** [comment]
@ShivaRapolu01 I don't see the point why I need to wait for the event. This is just like a few line config changes only. Therefore, I'd merge the PR whoever makes it first. or probably I could just solve it in my free time.

**Comment by sceary-expert** [comment]
@wingkwong I thought that I would solve this issue by myself but It's not as easy as I thought it would be as I have not worked with markdown pages. If you do this by yourself please let me know we might work on this together if you want.

**Comment by wingkwong** [comment]
@sceary-expert Didn't see that you self-assign. Maybe leave a comment next time. Basically this is just a configuration change. Anyone can just google and copy the config from the official doc. Probably just a 30-second work.

**Comment by i-dipanshu** [comment]
> @sceary-expert Didn't see that you self-assign. Maybe leave a comment next time. Basically this is just a configuration change. Anyone can just google and copy the config from the official doc. Probably just a 30-second work.

I'll make PR today, Just getting done with Classes

**Comment by wingkwong** [comment]
> > @sceary-expert Didn't see that you self-assign. Maybe leave a comment next time. Basically this is just a configuration change. Anyone can just google and copy the config from the official doc. Probably just a 30-second work.
> 
> I'll make PR today, Just getting done with Classes

Done and closed already.

**Comment by sceary-expert** [comment]
@wingkwong This issue was all about creating a button that can help to show the user main article and hides left menu (see the image below). I don't see that change has been made yet though you have closed the issue.
![image](https://user-images.githubusercontent.com/84634405/193243006-df2d5dee-6ee8-47a9-9fbd-dc954e0b23c4.png)

**Comment by wingkwong** [comment]
@sceary-expert 

![image](https://user-images.githubusercontent.com/35857179/193243713-f8b0a2e7-080e-4dc9-9808-66fecf749e2b.png)

![image](https://user-images.githubusercontent.com/35857179/193243775-772a2dcd-62a5-44a4-a48f-476ed9ad3991.png)

**Comment by sceary-expert** [comment]
> @sceary-expert
> 
> ![image](https://user-images.githubusercontent.com/35857179/193243713-f8b0a2e7-080e-4dc9-9808-66fecf749e2b.png)
> 
> ![image](https://user-images.githubusercontent.com/35857179/193243775-772a2dcd-62a5-44a4-a48f-476ed9ad3991.png)

Damnnnnnn!
