### ISSUE TITLE
Tutorial Writeup - MOD (1e9 + 7)

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#61]
Markdown Path: `tutorials/basic-topics/mod.md`

- Overview
- Why do we need to use MOD
- Why 1e9 + 7

You can include other info related to this topic as you wish.

**Comment by tannudaral** [comment]
Can I work on this?

**Comment by wingkwong** [comment]
Free feel to discuss the outline with me in Discord.
