### ISSUE TITLE
Tutorial Writeup - Binary Search Tree

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#62]
Markdown Path: `tutorials/graph-theory/binary-search-tree.md`

- Overview
- Explanation with 2 - 3 LC problems
- Suggested Problems (See `arrays.md` as a reference for the format)

You can include other info related to this topic as you wish.

**Comment by utkarsh4321** [comment]
@wingkwong can you assign me this issue? I wanted to work on this issue.

**Comment by wingkwong** [comment]
Free feel to discuss with me in Discord.

**Comment by utkarsh4321** [comment]
Hii I can't operate discord so can you clarify some doubts? 
1. How i will contribute to it?
2. First, I will fork this repo. And once my work is done then I will create a pull request. 
3. Is this the flow because the contribution guide has only tutorials and solutions guides nothing else?
So please clarify these doubts.

**Comment by wingkwong** [comment]
@utkarsh4321 

1. Fork this repository. Update the markdown. Then submit a PR.
2. Yes
3. The contribution guide is mainly for this repository. What you are asking is a general flow. If you are new to open source, you may check out some resources in hacktoberfest participation page [here](https://hacktoberfest.com/participation/)

**Comment by utkarsh4321** [comment]
@wingkwong I want to draw a binary search tree how i will draw it in markdown? can you give some suggestions?

**Comment by wingkwong** [comment]
Use some online tools to draw and then upload to GitHub editor to retrieve the img link.

**Comment by wingkwong** [comment]
Unassigned due to inactivity.

**Comment by ChiragAgg5k** [comment]
Hey there, i would like to work on this issue. Can you please assign me?

**Comment by wingkwong** [comment]
@ChiragAgg5k assigned. please check out contribution guide first.
