### ISSUE TITLE
Tutorial Writeup - Kruskal's Algorithm

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#65]
Markdown Path: `tutorials/graph-theory/kruskals-algorithm.md`

- Overview
- Explanation with 1 ~ 2 LC problems
- Suggested Problems (See `arrays.md` as a reference for the format)

You can include other info related to this topic as you wish.

**Comment by nithinaditya** [comment]
hey @wingkwong, I wish to work on this. Could you please assign this to me.

**Comment by wingkwong** [comment]
Free feel to ping me in Discord for discussion.

**Comment by wingkwong** [comment]
@nithinaditya Any updates?

**Comment by Po-Hsien39** [comment]
Hi @wingkwong, I wish I could take it on as well!

**Comment by wingkwong** [comment]
@nithinaditya Are you still working on it?

**Comment by Po-Hsien39** [comment]
Hi @wingkwong , I’m still waiting for this. Notify me anytime if the assignee is unassigned!

**Comment by wingkwong** [comment]
Removed @nithinaditya's assignment due to inactivity. 

@Po-Hsien39 Assigned. Please read [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) before working on it.

**Comment by Po-Hsien39** [comment]
Ok! Thanks very much! 😊

**Comment by wingkwong** [comment]
Unassigned due to inactivity.
