### ISSUE TITLE
Footer Enhancement

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [wingkwong/leetcode-the-hard-way#650]
**Description:**
The current footer design lacks some essential elements and could benefit from enhancements to improve both aesthetics and functionality. This issue aims to address these aspects for an overall better user experience.

**Enhancements:**
1. **Social Media Icons:** Add social media icons to the footer for easier access to our social profiles.
2. **Copyright Information:** Include the current year dynamically for the copyright information to stay up-to-date.
3. **Responsive Design:** Ensure that the footer maintains a polished appearance across various screen sizes and devices.

**Expected Behavior:**
The enhanced footer should be visually appealing, include the suggested elements, and maintain responsiveness across different devices.

**Additional Information:**
- This enhancement aligns with our efforts to create a more engaging and user-friendly interface.
- The changes should be consistent with the existing design language and brand guidelines.

Assign this to me under #hacktoberfest

**Comment by wingkwong** [comment]
2 & 3 seems already there. For 1, do you plan to remove the text and replace by icons instead?

**Comment by i-am-SnehaChauhan** [comment]
Yes, I will replace it with icons and give it a new look.

**Comment by wingkwong** [comment]
You may show a wireframe / mockup. So far I prefer to keep as text in footer thought. For icons, we already have them in header. Besides, it doesn't look good if you just replace social media links to icons while other links are texts.

**Comment by i-am-SnehaChauhan** [comment]
Thank you for your feedback and consideration. I understand the preference to keep the footer text-based and the existing presence of social media icons in the header.
Look at this footer design if you like it, I can proceed. 
![image](https://github.com/wingkwong/leetcode-the-hard-way/assets/94298791/f51a52c1-58bc-4f40-bb5d-3778202071a2)

**Comment by wingkwong** [comment]
IMO this layout doesn't suit the current site since it doesn't have many links and we can turn 3 links to icons only, which gives lots of empty space.

**Comment by i-am-SnehaChauhan** [comment]
It's OK if you don't like it. Thank you
