### ISSUE TITLE
Adding Footer and Front-End Improvements

### ISSUE THREAD

**Issue by Ajay-Dhangar** [wingkwong/leetcode-the-hard-way#652]
### Overview:
I would like to contribute to the "leetcode-the-hard-way" project by implementing a footer and enhancing the front-end user experience. This addition will not only improve the aesthetics of the website but also provide better navigation and engagement for users. 

### Proposed Changes:

**1. Footer Addition:**
   - **Implementation:** I plan to add containing essential information such as links to the project's documentation, contributor guidelines, and social media profiles, Resources, Compony, Product, Community , More.
   - **Benefits:** A footer will improve website navigation, making it easier for users to find important resources and information related to the project.

**2. Front-End Enhancements:**
   - **Implementation:** I intend to enhance the front-end by optimizing the layout, improving the responsiveness, and ensuring a consistent design throughout the website.
   - **Benefits:** These front-end improvements will create a more user-friendly and visually appealing experience for visitors, potentially increasing user engagement and satisfaction.

### How to I do Test:
To test these changes, you can follow these steps:
1. Clone the repository locally.
2. Checkout a new branch for this issue.
3. Implement the footer and front-end improvements.
4. Run the website locally and ensure that the footer is displayed correctly, and the front-end enhancements are noticeable.
5. Verify that the changes do not introduce any new bugs or issues.

### Additional Information:
 
***For Demo:***

![image](https://github.com/wingkwong/leetcode-the-hard-way/assets/99037494/a036b896-58d6-4e36-8d4a-a8c797e0dbf4)

### Related Issues:
None

**Comment by wingkwong** [comment]
1. For footer, please list out all the categories and links using our site as an example. So far I don't think we got many links for that. Also, site views, codeQL and stars buttons seems not necessary in this site.

2. how would you implement it on top of docusaurus?

**Comment by Ajay-Dhangar** [comment]
can you assign me for working on this repo

and i fond out one more issue for response device ( size 1000 to 1110 )

![Screenshot 2023-10-02 124036](https://github.com/wingkwong/leetcode-the-hard-way/assets/99037494/6d97ef08-70f8-4c50-a425-9070013af5f4)

**Comment by Ajay-Dhangar** [comment]
Thank you for taking the time to review my work. I'm open to any feedback or suggestions for updates to improve it further. If you believe that additional links or code would enhance the project, I've already set up the groundwork to make these additions seamlessly accessible for anyone who wants to contribute.

I'm confident in the quality of my work, so if you find it suitable, I would appreciate it if you could consider merging it into the main branch. However, if there's any specific feature you'd like to see or if you require any assistance with the integration, please don't hesitate to reach out. I'm here to help and collaborate to make this project even better.

**Comment by wingkwong** [comment]
handled in #655.
