### ISSUE TITLE
Tutorial Writeup - Combinatorics

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#68]
Markdown Path: `tutorials/math/combinatorics.md`

- Overview
- Explanation with 1 ~ 2 LC problems
- Suggested Problems (See `arrays.md` as a reference for the format)

You can include other info related to this topic as you wish.

**Comment by Vaani-pathariya** [comment]
Hello @wingkwong ,can I be assigned this issue and can this one be considered under hacktober fest ?

**Comment by wingkwong** [comment]
Sure. Yes.

**Comment by BlackPanther112358** [comment]
Hi, @wingkwong, can you assign me this issue ?

**Comment by wingkwong** [comment]
@Vaani-pathariya Just to confirm. Are you not working on this issue?

**Comment by Vaani-pathariya** [comment]
No , not right now ,you can assign it to someone else .Thank you !

**Comment by wingkwong** [comment]
@BlackPanther112358 You have it now.

**Comment by BlackPanther112358** [comment]
On it

**Comment by BlackPanther112358** [comment]
Hi @wingkwong, while looking for materials on the topic, I noticed that the solutions for following problems are not up yet:

1. 458 Poor Pigs (https://leetcode.com/problems/poor-pigs)
2. 1863 Sum of All Subset XOR Totals (https://leetcode.com/problems/sum-of-all-subset-xor-totals)
3. 2221 Find Triangular Sum of an Array (https://leetcode.com/problems/find-triangular-sum-of-an-array)
4. 1467 Probability of a Two Boxes Having The Same Number of Distinct Balls (https://leetcode.com/problems/probability-of-a-two-boxes-having-the-same-number-of-distinct-balls)

Should I add solutions for the above problems ?

**Comment by wingkwong** [comment]
You can either add them or leave solutionLink blank

**Comment by BlackPanther112358** [comment]
I will be submitting solutions to these questions as I am making tutorial based on these, So I easily add solutions to these problems in C++ and Python.
