### ISSUE TITLE
Tutorial Writeup - Prime Factors

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#69]
Markdown Path: `tutorials/math/prime-factors.md`

- Overview
- Explanation with 2 ~ 3 LC problems
- Suggested Problems (See `arrays.md` as a reference for the format)

You can include other info related to this topic as you wish.

**Comment by abhishek-sultaniya** [comment]
Hello @wingkwong ,I would like to work on this issue.It would be great if you will assign me this.

**Comment by wingkwong** [comment]
Assigned. Feel free to discuss with me in Discord.

**Comment by UjjwalAggarwal-1** [comment]
so is it under process or may i take it up? under hacktoberfest, that is

**Comment by wingkwong** [comment]
@abhishek-sultaniya Any update?

**Comment by abhishek-sultaniya** [comment]
> @abhishek-sultaniya Any update?

Sorry,I am not able to complete it on time.Little busy due to some other works .Please assign it to @UjjwalAggarwal-1

**Comment by wingkwong** [comment]
@UjjwalAggarwal-1 Assigned. Please look at [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) first.

**Comment by wingkwong** [comment]
Unassigned due to inactivity.

**Comment by charann29** [comment]
If there isn't anyone currently assigned to this task, I'd like to take it on. Kindly assign this issue to me, @wingkwong

**Comment by wingkwong** [comment]
@charann29 Assigned. Please look at [CONTRIBUTING.md](https://github.com/wingkwong/leetcode-the-hard-way/blob/main/CONTRIBUTING.md) first.

**Comment by Ishwarendra** [comment]
If no one is working, I can take up this issue. I have following things in mind
1. How to find prime factors naively in $n \cdot log(n)$ time and then optimising it to $\sqrt{n}$.
2. Basic idea about why number of prime factors cannot exceed $log(n)$.
3. Special case where numbers are small $< 10^7$. We can first use sieve to find `min_prime[i] = smallest prime factor of i` for each $i \in [2, n]$. 

Problem List:
1. [2521. Distinct Prime Factors Product of Array](https://leetcode.com/problems/distinct-prime-factors-of-product-of-array/description/)
2. [2507. Smallest Value After Replacing with Sum of Prime Factors](https://leetcode.com/problems/smallest-value-after-replacing-with-sum-of-prime-factors/description/)
3. [952. Largest Component Size by Common Factor](https://leetcode.com/problems/largest-component-size-by-common-factor/description/)

Practice Problem:
1. [263. Ugly Number](https://leetcode.com/problems/ugly-number/description/)
2. [650. 2 Keys Keyboard](https://leetcode.com/problems/2-keys-keyboard/description/)
3. [1627. Graph Connectivity with threshold](https://leetcode.com/problems/graph-connectivity-with-threshold/description/)
4. [2709. Greatest Common Divisor Traversal](https://leetcode.com/problems/greatest-common-divisor-traversal/description/)

**Comment by wingkwong** [comment]
reassigned to @Ishwarendra due to inactivity.
