### ISSUE TITLE
Disjoint Set Union (DSU) Page Example Not Displaying Correctly

### ISSUE THREAD

**Issue by DerekLieww** [wingkwong/leetcode-the-hard-way#714]
On the page Disjoint Set Union, The example of what is a disjoint set or not is displaying differently from the MD on github.

on https://leetcodethehardway.com/tutorials/graph-theory/disjoint-set-union 
```
A set is a collection of elements. If two sets have no common elements, then they are called disjoint sets.
For example, 2 and 4 are disjoint sets while 2 and 3 are not because they have a common element 1.
```
vs on github 
https://github.com/wingkwong/leetcode-the-hard-way/blob/main/tutorials/graph-theory/disjoint-set-union.md
```
A set is a collection of elements. If two sets have no common elements, then they are called disjoint sets. 
For example, {1, 2} and {3, 4} are disjoint sets while {1, 2} and {1, 3} are not because they have a common element 1.
```

The example on the live website is only a single item of the sets instead of the whole of each set.

**Comment by wingkwong** [comment]
Good catch.
