### ISSUE TITLE
Tutorial Writeup - Dynamic Programming

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#73]
Markdown Path: `tutorials/dynamic-programming.md`

- Overview
- Explanation with 1 ~ 2 LC problems
- Suggested Problems (See `arrays.md` as a reference for the format)

You can include other info related to this topic as you wish.

**Comment by wingkwong** [comment]
Free feel to ping me to discuss in Discord.

**Comment by M-Rahul1** [comment]
i would like to contribute. This would be my first PR in hacktoberfest @wingkwong

**Comment by wingkwong** [comment]
@M-Rahul1 You may check with @Cyber-Machine

**Comment by wingkwong** [comment]
Oh yes. Should've linked the issue in PR. Yes. @M-Rahul1 You can add more content if you want.
