### ISSUE TITLE
Tutorial Writeup - Greedy

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#75]
Markdown Path: `tutorials/basic-topics/greedy.md`

- Overview
- Explanation with 1 ~ 2 LC problems
- Suggested Problems (See `arrays.md` as a reference for the format)

You can include other info related to this topic as you wish.

**Comment by abhishek-sultaniya** [comment]
Hello @wingkwong ,I would like to work on this issue.It would be great if you will assign me this.
