### ISSUE TITLE
Tutorial Writeup - Matrix Exponentiation

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#77]
Markdown Path: `tutorials/math/matrix-exponentiation.md`

- Overview
- Explanation with 2 - 3 LC problems
- Suggested Problems (See `arrays.md` as a reference for the format)

You can include other info related to this topic as you wish.

**Comment by abhishek-sultaniya** [comment]
Hello @wingkwong ,I would like to work on this issue.It would be great if you will assign me this.

**Comment by wingkwong** [comment]
@abhishek-sultaniya Any updates?

**Comment by TheCodeAlpha26** [comment]
Hey @wingkwong , I would like to work on this issue if its possible

**Comment by wingkwong** [comment]
@abhishek-sultaniya Are you still working? if there is no reply for 24 hours, I'll assign to @TheCodeAlpha26 .

**Comment by wingkwong** [comment]
Unassigned due to inactivity.

**Comment by Ishwarendra** [comment]
Hi @wingkwong I would like to work up on this issue.
Problems:
- https://leetcode.com/problems/fibonacci-number/description/ (in tutorial)
- https://leetcode.com/problems/n-th-tribonacci-number/description/ (as suggested problem)
- https://leetcode.com/problems/count-vowels-permutation/description/ (in tutorial)

If problem other than leetcode is allowed then I would suggest this problem which only asks to find $n^{th}$ fibonacci term but  the constraints doesn't allow linear dynamic programming solution to pass.

**Comment by wingkwong** [comment]
those 2 problems are fine. I'd not recommend to include problems from external source.
