### ISSUE TITLE
Tutorial Writeup - Merge Sort

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#91]
Markdown Path: `tutorials/basic-topics/sorting/merge-sort.md`

- Overview
- Explanation with 1 ~ 2 LC problems
- Suggested Problems (See `arrays.md` as a reference for the format)

You can include other info related to this topic as you wish.

**Comment by Sreetama2001** [comment]
Can you assign please this issue to me @wingkwong  , I am working on this.

**Comment by wingkwong** [comment]
@Sreetama2001 sure. free feel to ping me in Discord for discussion.
