### ISSUE TITLE
Dark Mode Style Refactoring

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#92]
The color in dark mode is quite bad currently. Need some better colors for it.

**Comment by Dun-sin** [comment]
Hi, what about this color?

![image](https://user-images.githubusercontent.com/78784850/193313092-47176d38-f1c5-45b2-9dac-2c1b37510be3.png)

**Comment by itsmenikhill** [comment]
![image](https://user-images.githubusercontent.com/44477975/193319698-76763de6-b10d-4c67-b0f4-af5943a667e2.png)

how about this?

**Comment by wingkwong** [comment]
The cover page can be skipped atm. I plan to add some content on the landing page instead of just pasting an image there. It's more on the content for this issue.

**Comment by i-dipanshu** [comment]
> The color in dark mode is quite bad currently. Need some better colors for it.

Yeah, the contrast is bad.
My Few Suggestions:
- The One Twitter Uses - `#15202b`
- The One GitHub Uses - `#22272e`
These gives a good reading experience especially in long sessions.

**Comment by i-dipanshu** [comment]
Hey @wingkwong 
Check out implemented samples I send you over on discord 
We could also change the font size and font family say `Roboto` better reading experience.
Could you please assign me this task

**Comment by i-dipanshu** [comment]
> Hey @wingkwong Check out implemented samples I send you over on discord We could also change the font size and font family say `Roboto` better reading experience.
Could you please assign me this task

**Comment by i-dipanshu** [comment]
Hey @wingkwong 
Could you please assign me this task

**Comment by wingkwong** [comment]
@i-dipanshu you got two tasks on hand already. I'd like to give more chances to other new contributors. Of course you can leave suggestions here.

**Comment by atom540** [comment]
hey, I want to work on this topic because I make dark mode on the website in my project. so, can you assign this topic to me?

**Comment by wingkwong** [comment]
@atom540 Assigned

**Comment by wingkwong** [comment]
@atom540 Any updates?

**Comment by wingkwong** [comment]
Unassigned due to inactivity.

**Comment by wingkwong** [comment]
Closing - not applicable now due to UI change.
