### ISSUE TITLE
Tutorial Writeup - Bubble Sort

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#93]
Markdown Path: `tutorials/basic-topics/sorting/bubble-sort.md`

- Overview
- Explanation with 1 ~ 2 LC problems
- Suggested Problems (See `arrays.md` as a reference for the format)

You can include other info related to this topic as you wish.

**Comment by i-dipanshu** [comment]
Hey @wingkwong 
Could you please assign this task to me

**Comment by RadhikaChhabra17** [comment]
Hi, I am interested in this task. Can you please assign this to me?

**Comment by i-dipanshu** [comment]
@wingkwong 
Please do assign her this task, 
I'd really busy with DLL

**Comment by wingkwong** [comment]
Assigned to @RadhikaChhabra17 instead.

**Comment by wingkwong** [comment]
@RadhikaChhabra17 Any updates?

**Comment by Ritvik-2002** [comment]
@wingkwong could you assign it to me ?
