### ISSUE TITLE
Tutorial Writeup - Insertion Sort

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#95]
Markdown Path: `tutorials/basic-topics/sorting/insertion-sort.md`

- Overview
- Explanation with 1 ~ 2 LC problems
- Suggested Problems (See `arrays.md` as a reference for the format)

You can include other info related to this topic as you wish.

**Comment by Sreetama2001** [comment]
@wingkwong  Want to work on insertion sort since I am already working on other sorting algos. So can you please assign me this?

**Comment by wingkwong** [comment]
@Sreetama2001 I think it'd better to leave it to other new contributors as you have two writeups already. I try to keep each contributor to have at most 2 tasks on hand. Of course if you've finished one of them and this still remains unassigned, then you can take it.

**Comment by Sreetama2001** [comment]
> @Sreetama2001 I think it'd better to leave it to other new contributors as you have two writeups already. I try to keep each contributor to have at most 2 tasks on hand. Of course if you've finished one of them and this still remains unassigned, then you can take it.

ohk sure ! 😇

**Comment by Shivashish-rwt** [comment]
I wanna work on this. Can u please assign this to me.

**Comment by Bobliuuu** [comment]
@wingkwong I'd love to contribute to this. Could you please assign this to me?

**Comment by wingkwong** [comment]
I'll let [Shivashish-rwt](https://github.com/Shivashish-rwt) do it. (based on the number of tasks on hand and the time to request assignment)

**Comment by Shivashish-rwt** [comment]
Thanks for assiging me.

**Comment by Shivashish-rwt** [comment]
@wingkwong I have commited the changes required. Please review my PR.
