### ISSUE TITLE
Tutorial Writeup - Selection Sort

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#96]
Markdown Path: `tutorials/basic-topics/sorting/selection-sort.md`

- Overview
- Explanation with 1 ~ 2 LC problems
- Suggested Problems (See `arrays.md` as a reference for the format)

You can include other info related to this topic as you wish.

**Comment by flow6979** [comment]
hey @wingkwong, I want to contribute to this issue. can you please assign this to me?

**Comment by Bobliuuu** [comment]
Hey @wingkwong, Could I contribute to this issue?

**Comment by wingkwong** [comment]
I'll let @Bobliuuu to take this as he is new and @flow6979 got one task already.
