### ISSUE TITLE
Tutorial Writeup - Shell Sort

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#97]
Markdown Path: `tutorials/basic-topics/sorting/shell-sort.md`

- Overview
- Explanation with 2 - 3 LC problems
- Suggested Problems (See `arrays.md` as a reference for the format)

You can include other info related to this topic as you wish.

**Comment by ganajayant** [comment]
Can i get this issue

**Comment by wingkwong** [comment]
@ganajayant Assigned

**Comment by wingkwong** [comment]
@ganajayant Any updates?

**Comment by ganajayant** [comment]
i am till busy these days so i can't complete sorry for the inconvenience please assign somebody else

**Comment by jadhav-kunal** [comment]
Hey, i've been solving few problems on LeetCode, might as well contribute. can you please assign it to me?

**Comment by wingkwong** [comment]
@jadhav-kunal provide 2 submission links from 2 problems that you solve with shell sort

**Comment by Saishreekouda** [comment]
can you assign this issue to me under hacktoberfest?

**Comment by wingkwong** [comment]
@Saishreekouda provide 2 submission links from 2 problems that you solve with shell sort

**Comment by Saishreekouda** [comment]
1. Sort an array- https://leetcode.com/problems/sort-an-array/submissions/1066575824/
2. Merge 2 sorted arrays- https://leetcode.com/problems/merge-sorted-array/submissions/1066573172/

**Comment by wingkwong** [comment]
@Saishreekouda assigned. please check out the contribution guide first.
