### ISSUE TITLE
Tutorial Writeup - Linked List

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/leetcode-the-hard-way#98]
Markdown Path: `tutorials/basic-topics/linked-list.md`

- Overview
- Explanation with 1 ~ 2 LC problems
- Suggested Problems (See `arrays.md` as a reference for the format)

You can include other info related to this topic as you wish.

**Comment by wingkwong** [comment]
Reserved for [itsmenikhill](https://github.com/itsmenikhill)

**Comment by itsmenikhill** [comment]
Hey, I would like to work on this.

**Comment by Abhinav-J05** [comment]
hey! I loved this topic and I would like to contribute to this, please assign this issue to me.
thank you!

**Comment by wingkwong** [comment]
@Abhinav-J05 sorry. the issue's taken already.
